// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/baby.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7423850304965481178),
      name: 'Baby',
      lastPropertyId: const IdUid(7, 2806138200074544793),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5432533755943320368),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1062643380260296953),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5936027595964505485),
            name: 'dob',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3588220535118425765),
            name: 'weight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 110147582756525806),
            name: 'gender',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 350131684834060705),
            name: 'height',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2806138200074544793),
            name: 'imagePath',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7423850304965481178),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Baby: EntityDefinition<Baby>(
        model: _entities[0],
        toOneRelations: (Baby object) => [],
        toManyRelations: (Baby object) => {},
        getId: (Baby object) => object.id,
        setId: (Baby object, int id) {
          object.id = id;
        },
        objectToFB: (Baby object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final genderOffset = fbb.writeString(object.gender);
          final imagePathOffset = object.imagePath == null
              ? null
              : fbb.writeString(object.imagePath!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.dob.millisecondsSinceEpoch);
          fbb.addFloat64(3, object.weight);
          fbb.addOffset(4, genderOffset);
          fbb.addFloat64(5, object.height);
          fbb.addOffset(6, imagePathOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dobParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final weightParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final genderParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final heightParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final object = Baby(
              id: idParam,
              name: nameParam,
              dob: dobParam,
              weight: weightParam,
              gender: genderParam,
              height: heightParam,
              imagePath: imagePathParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Baby] entity fields to define ObjectBox queries.
class Baby_ {
  /// see [Baby.id]
  static final id = QueryIntegerProperty<Baby>(_entities[0].properties[0]);

  /// see [Baby.name]
  static final name = QueryStringProperty<Baby>(_entities[0].properties[1]);

  /// see [Baby.dob]
  static final dob = QueryIntegerProperty<Baby>(_entities[0].properties[2]);

  /// see [Baby.weight]
  static final weight = QueryDoubleProperty<Baby>(_entities[0].properties[3]);

  /// see [Baby.gender]
  static final gender = QueryStringProperty<Baby>(_entities[0].properties[4]);

  /// see [Baby.height]
  static final height = QueryDoubleProperty<Baby>(_entities[0].properties[5]);

  /// see [Baby.imagePath]
  static final imagePath =
      QueryStringProperty<Baby>(_entities[0].properties[6]);
}
